apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: server-viewer
spec:
  action: DENY
  rules:
  - to:
    - operation:
        methods: ["GET"]
        ports: ["8080"]
